### ISSUE TITLE
RFE: Ability to chose path for temp file on write_videofile

### ISSUE THREAD

**Issue by soeirodefaria** [Zulko/moviepy#892]
I'm trying to use moviepy on a Google Cloud Function (similar do AWS Lambda) and can't get around this problem. Even though I can download the original movie and save the resized movie, in an specified directory, the operation fails because write_videofile creates a temp file wherever the code is running. On GCF's case it runs on a read-only fs, which makes the operation impossible.
The ability to chose where to store the temp file would be huge.

**Comment by lincolnaleixo** [comment]
I would love to have that too

**Comment by tburrows13** [comment]
Thank you for the interest. I've added it in #1144, so it should be included in v2.0. In the meantime, you can use the `temp_audiofile` parameter yourself with any path. The only catch is that you have to generate the filename yourself as well.

**Comment by escoolioinglesias** [comment]
@tburrows13 

is temp_audiofile_path deprecated?

I'm getting 

```
% TypeError: write_videofile() got an unexpected keyword argument 'temp_audiofile_path'
```

**Comment by malay77patra** [comment]
> @tburrows13
> 
> is temp_audiofile_path deprecated?
> 
> I'm getting
> 
> ```
> % TypeError: write_videofile() got an unexpected keyword argument 'temp_audiofile_path'
> ```

I dont think you have the right version, cuz its not relesed yet 
refrence:
MoviePy v2.0 has undergone some large changes with the aim of making the API more consistent and intuitive. There is a high likelihood that your pre-v2.0 programs will not run without some changes. Almost all of the changes are ‘surface-level’, so usually all you’ll need to do is a “Find and Replace” on the class, method, and parameter names that have been changed.

**Comment by early-riser18** [comment]
@escoolioinglesias It still works for me on v 1.0

**Comment by bendsouza2** [comment]
> @tburrows13
> 
> is temp_audiofile_path deprecated?
> 
> I'm getting
> 
> ```
> % TypeError: write_videofile() got an unexpected keyword argument 'temp_audiofile_path'
> ```

the argument is `temp_audiofile`, not `temp_audiofile_path` - it should still work on v 1.0.3 at least

**Comment by tburrows13** [comment]
v1.0.3 only has `temp_audiofile`.
v2.x has both `temp_audiofile` (for the name of the file) and `temp_audiofile_path` (for the location/path to put the file in), as explained in the docs: https://zulko.github.io/moviepy/reference/reference/moviepy.video.VideoClip.VideoClip.html#moviepy.video.VideoClip.VideoClip.write_videofile

If you are getting ```
TypeError: write_videofile() got an unexpected keyword argument 'temp_audiofile_path'```
then make sure you update to 2.x, and see the following page for help doing so: https://zulko.github.io/moviepy/getting_started/updating_to_v2.html
