### ISSUE TITLE
AttributeError: 'AudioClip' object has no attribute 'preview'

### ISSUE THREAD

**Issue by DarkRedman** [Zulko/moviepy#2289]
#### Expected Behavior

I expect to hear the audio on preview

#### Actual Behavior

I get this error `AttributeError: 'AudioClip' object has no attribute 'preview'`

#### Steps to Reproduce the Problem

I use the code straight from the documentation [moviepy.audio.AudioClip.AudioClip](https://zulko.github.io/moviepy/reference/reference/moviepy.audio.AudioClip.AudioClip.html#moviepy.audio.AudioClip.AudioClip)

```py
# Plays the note A in mono (a sine wave of frequency 440 Hz)
import numpy as np
frame_function = lambda t: np.sin(440 * 2 * np.pi * t)
clip = AudioClip(frame_function, duration=5, fps=44100)
clip.preview()

# Plays the note A in stereo (two sine waves of frequencies 440 and 880 Hz)
frame_function = lambda t: np.array([
    np.sin(440 * 2 * np.pi * t),
    np.sin(880 * 2 * np.pi * t)
]).T.copy(order="C")
clip = AudioClip(frame_function, duration=3, fps=44100)
clip.preview()
```

#### Specifications

  - Python Version: 3.12.7
  - MoviePy Version: 2.1.1
  - Platform Name: Linux
  - Platform Version: 6.6.63-1-MANJARO
  
  #### Additional Notes

I also tried the audiopreview() method on the AudioClip and I get this traceback

```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    test_audio()
  File "main.py", line 68, in test_audio
    clip.audiopreview()
  File "<decorator-gen-47>", line 2, in audiopreview
  File "/usr/lib/python3.12/site-packages/moviepy/decorators.py", line 53, in requires_duration
    return func(clip, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/moviepy/audio/AudioClip.py", line 301, in audiopreview
    ffplay_audiopreview(
  File "<decorator-gen-11>", line 2, in ffplay_audiopreview
  File "/usr/lib/python3.12/site-packages/moviepy/decorators.py", line 53, in requires_duration
    return func(clip, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/moviepy/audio/io/ffplay_audiopreviewer.py", line 154, in ffplay_audiopreview
    previewer.write_frames(chunk)
  File "/usr/lib/python3.12/site-packages/moviepy/audio/io/ffplay_audiopreviewer.py", line 68, in write_frames
    self.logfile.seek(0)
    ^^^^^^^^^^^^
AttributeError: 'FFPLAY_AudioPreviewer' object has no attribute 'logfile'
```

**Comment by OsaAjani** [comment]
Just tried and audiopreview seems to work with latest version (2.1.2), can you confirm (also I just lost hearing in my left ear and my dog is howling in the corner of the room...).

**Comment by 9uvi** [comment]
Hi, I'm having the same issue with the latest version too (2.1.2). I'm following the "MoviePy in 10 minutes" tutorial so everything should be up to date as I installed the dependencies today.

**Comment by OsaAjani** [comment]
The MoviePy in 10 minutes tutorial does not include any usage of preview on audio clip, only on video clip. If you want to preview an audio clip you can use the function [audiopreview](https://zulko.github.io/moviepy/reference/reference/moviepy.audio.AudioClip.AudioClip.html#moviepy.audio.AudioClip.AudioClip.audiopreview)

**Comment by Freyb** [comment]
@OsaAjani looking at the tracelog `.audiopreview()` is also failing.

I got the that error too, which might be caused by an ffplay version.
Versions:
- moviepy 2.1.2
- ffplay 7.1 (Mac)

The problem is that ffplay no longer have `-ac` flag, it was replace by `-ch_layout` (valid values: `-ch_layout mono` and `-ch_layout stereo`)

This causes `FFPLAY_AudioPreviewer.write_frames` to fail at: https://github.com/Zulko/moviepy/blob/ed7dfedb2d22d7fdc73085c2825cfc710d67d0d7/moviepy/audio/io/ffplay_audiopreviewer.py?plain=1#L60

However, as the tracelog says, there is another problem. `FFPLAY_AudioPreviewer` does not have a `logfile` attribute, so during the handling of the previous error, an `AttributeError` will be raised at:
https://github.com/Zulko/moviepy/blob/ed7dfedb2d22d7fdc73085c2825cfc710d67d0d7/moviepy/audio/io/ffplay_audiopreviewer.py?plain=1#L68

The first problem can be solved by rewriting `cmd` in `FFPLAY_AudioPreviewer` constructor.
```
-            "-ac",
-            "%d" % nchannels,
+            "-ch_layout",
+            ["mono", "stereo"][nchannels - 1],
```
Of course not the most elegant solution, as older ffplay still uses `-ac` but a quick workaround.

**Comment by OsaAjani** [comment]
Okay, the. I will take a look as soon as I can we have :)

**Comment by OsaAjani** [comment]
Hi, this is fixed with PR #2331
