### ISSUE TITLE
TypeError using `progress_bar` arg in VideoFileClip.write_videofile()

### ISSUE THREAD

**Issue by N2ITN** [Zulko/moviepy#910]
### Expected Behavior
```
from moviepy.editor import VideoFileClip

VideoFileClip('video.mp4').write_videofile(
        output_video_path,
        verbose=True,
        progress_bar=True,
        ffmpeg_params=ffmpeg_params)
```

This worked fine using version 0.2.5.3
After the recent 1.0.0 upgrade, the same code now throws an error. I don't see a reference to the `progress_bar` in the current source code except for in comments.
Reverting to 0.2.5.3 seems to fix the issue.

### Actual Behavior
`TypeError("write_videofile() got an unexpected keyword argument 'progress_bar'",)`

### Steps to Reproduce the Problem

```
from moviepy.editor import VideoFileClip

VideoFileClip('video.mp4').write_videofile(
        output_video_path,
        verbose=True,
        progress_bar=True,
        ffmpeg_params=ffmpeg_params)
```
### Specifications

  - Python Version: 3.6
  - Moviepy Version: 1.0.0 
  - Platform Name: Ubuntu 
  - Platform Version: 16.04

**Comment by Zulko** [comment]
The progress bar management is the main non-backward-compatible change introduced in 1.0.0. The "progress_bar" argument was replaced by a "logger" argument (which can be either ``"bar"`` or ``None`` or any [Proglog](https://github.com/Edinburgh-Genome-Foundry/Proglog) logger).

I put a note about it at the end of the README, but I haven't updated the docs yet.

In your case, just removing the line ``progress_bar=True`` should work.

**Comment by N2ITN** [comment]
Thanks! I saw that progress bar is now enabled by default in the "logger" argument, so I commented out the "progress_bar" argument and it works now as you said.

**Comment by wookayin** [comment]
https://github.com/Zulko/moviepy#new-in-100-progress-bars-and-messages-with-proglog

How to disable progress bar?

**Comment by Zulko** [comment]
Try "logger=None"

**Comment by wookayin** [comment]
I get `write_videofile() got an unexpected keyword argument 'logger'` (this method also had `progress_bar` keyword argument but 1.0.0 has not add its replacement, `logger`). Please check the API changes on all methods that had `progress_bar`!

**Comment by bscs17047** [comment]
progress_bar = False

This line of code will disable progress bar printing.

But I'll not recommend that.

**Comment by nabinbhusal80** [comment]
For moviepy==1.0.3

use 

`logger=None`

**Comment by steinathan** [comment]
@keikoro thanks, this helps
